### ISSUE TITLE
How to identify returned waypoints with the ones that were passed into RouteOptions?

### ISSUE THREAD

**Issue by rmnblm** [mapbox/MapboxDirections.swift#116]
I'm looking for a way to identify the returned waypoints with the ones that were passed into the RouteOptions. 

``` swift
let options = RouteOptions(waypoints: waypoints, profileIdentifier: MBDirectionsProfileIdentifier.cycling)
options.includesSteps = true

task = directions.calculate(options) { [unowned self] (waypoints, routes, error) in

}
```

I first tried to set a name for each Waypoint, but the names of the returned waypoints are different to the ones set.

Other options are:
* **If** the count of the passed in waypoints is exactly the same as the ones returned from the service, I can map them by their indices. Is this the case?
* If the first options is answered with no, then I could compare the coordinates of the returned waypoints with the ones passed into the RouteOptions, but I don't think that would be performant and comparing floating numbers is always a problem.
* Any other ideas?

What is the recommended solution for this use case?

**Comment by 1ec5** [comment]
> If the count of the passed in waypoints is exactly the same as the ones returned from the service, I can map them by their indices. Is this the case?

The waypoints are provided by OSRM via the Directions API, so they aren’t literally the same objects you initialized RouteOptions with. However, their indices should match; that is, the second item in the closure’s `waypoints` parameter corresponds to the second item in the `waypoints` array you provided, even if their names may not match. (Their coordinates may not match, either, due to OSRM snapping the request to the road network.) That second item is literally the same object as the first leg’s `destination` and the second leg’s `source`.

**Comment by rmnblm** [comment]
> However, their indices should match; that is, the second item in the closure’s waypoints parameter corresponds to the second item in the waypoints array you provided, even if their names may not match.

@1ec5 Thanks for clarification, that's what I wanted to hear. 😊
