### ISSUE TITLE
Misleading route directions

### ISSUE THREAD

**Issue by aodhol** [mapbox/MapboxDirections.swift#186]
Users have reported several instances in our App of text instructions being at odds with the line drawn on the map representing the route.

![image uploaded from ios](https://user-images.githubusercontent.com/274682/31414534-46e27360-ae16-11e7-8a6e-f5b6a358cada.png)

- iOS 11.0  
- MapboxDirections.swift 0.10.5 
- Cycling profile identifier.

The directions request, re-routing and text instructions code is based on the sample App.

**Comment by 1ec5** [comment]
The route travels down cycling sidepaths that run parallel to Whitechapel Road. At [the complex intersection](https://www.openstreetmap.org/#map=19/51.51852/-0.06284) with Vallance and New roads, it looks like the route technically turns a couple times in order to get to the other side of the road. I guess that’s what the instruction is saying. If you look at the previous step’s `instructionsDisplayedAlongStep`, you might see a tertiary instruction that you could interpret as a “then” clause.

Overall, neither OSRM nor Valhalla do a great job of generalizing micromapped sidepaths and crosswalks into a narrative based on the main roadways. However, if these spurious instructions are proving problematic for you, one workaround would be to decrease the `RouteOptions.walkwayPriority` property to the point that the instructions avoid these sidepaths in favor of the main roadways. That’s not to say your users have to use the main traffic lanes, but they’ll interpret the route as a bit of an abstraction and know to use nearby segregated cycling facilities.
