### ISSUE TITLE
How to show route on map?

### ISSUE THREAD

**Issue by Sh1mor1nka** [mapbox/MapboxDirections.swift#21]

**Comment by 1ec5** [comment]
If you’re using the Mapbox iOS SDK in conjunction with this library, you’d call `MBDirections.calculateDirectionsWithCompletionHandler(_:)` to get an MBRoute, then convert its `geometry` into an MGLPolyline that you can then add to an MGLMapView.

As part of [our mobile navigation SDK effort](https://www.mapbox.com/blog/mobile-navigation/), we’re working on expanding our iOS SDK so that, among other things, you won’t have to perform that conversion step yourself.
