### ISSUE TITLE
Read API base URL from Info.plist

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#283]
If no `host` is passed into `Directions(accessToken:host:)`, the fallback hostname should be either api.mapbox.com or api.mapbox.cn depending on the value of `MGLMapboxAPIBaseURL` in Info.plist:

https://github.com/mapbox/MapboxDirections.swift/blob/586f6c57b887856b5af9a99b235115facc73bdfa/MapboxDirections/MBDirections.swift#L146

This would be consistent with how we read the access token out of Info.plist:

https://github.com/mapbox/MapboxDirections.swift/blob/586f6c57b887856b5af9a99b235115facc73bdfa/MapboxDirections/MBDirections.swift#L139

This will make it easier for developers to keep their map and directions usage in sync, since `Directions.shared` would automatically pick up the API endpoint specified in Info.plist. Developers who need a different value for the Directions API can still override the API base URL when creating a separate `Directions` instance.

/ref mapbox/MapboxGeocoder.swift#107
/cc @m-stephen @chriswu42

**Comment by bsudekum** [comment]
At first blush, I'm sort left wondering why not just pass `api.mapbox.cn ` through when initing Directions. But I guess it could be set once in the plist and everything could look there. What if someone passes a host through when initing Directions and there is also a value in the plist? Who wins?

**Comment by 1ec5** [comment]
Yes, the idea is that setup for various services should normally be centralized in Info.plist. As described above, a hostname explicitly passed into the initializer would override the value in Info.plist, just as with access tokens.

**Comment by m-stephen** [comment]
I think this issue is blocked by the server side now.

Because the api direction .cn is a very old version of api direction .com now. After discussing with @tony-cj, the ECS server has not been set up in China. Now they are working for that. It will take a few weeks for ready.

As you know, the api direction cn lack of some parameters than the api direction .com(Actually 4 parameters: `roundabout_exits`,`voice_instructions`,`voice_units` and `banner_instructions`). And if you use the current SDK to request the api direction cn, the server just return failure because of the redundant parameters.

I can make a PR to modify the codes on the mobile side at first, but if the server is not ready, the codes still cannot work.

@1ec5 @bsudekum

**Comment by 1ec5** [comment]
> I can make a PR to modify the codes on the mobile side at first, but if the server is not ready, the codes still cannot work.

There’s no rush, then, but if you have some spare cycles, then we can get this change out of the way so it’ll just work once the server is ready. Without the change, using `.shared` with a .cn access token in Info.plist is going to cause authorization errors anyways.
