### ISSUE TITLE
Truncate precision in `CLLocationCoordinate2D` to relevant decimal places

### ISSUE THREAD

**Issue by JThramer** [mapbox/MapboxDirections.swift#309]
When crafting a custom `RouteOptions` request , the user has the ability to use the full `Double` bitwidth to describe `CLLocationCoordinate2D` waypoints. This causes us to potentially emit really long requests when we end up requesting a route.

We only pay attention to the the fifth or sixth decimal place in the API (depending on the API version I think? cc @1ec5), so we should truncate our values to match at request time.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> We only pay attention to the the fifth or sixth decimal place in the API (depending on the API version I think?)

OSRM uses [up to six digits of precision](https://github.com/Project-OSRM/osrm-backend/blob/82b5648c97edf1d2edec7aecebc35aa8a8033c82/include/util/coordinate.hpp#L44). That has been the case [since at least OSRM v0.3.8](https://github.com/Project-OSRM/osrm-backend/blob/8e6cc09d2f442b10fc375c2ea9e9c3b41cb51522/Include/osrm/Coordinate.h#L33), which came before Directions API v4, the first version of the API that this library supported.

**Comment by 1ec5** [comment]
This is where we’d round then truncate:

https://github.com/mapbox/MapboxDirections.swift/blob/6bf93daa11ed21b2b31352f199ac1316fb1c287b/MapboxDirections/MBDirectionsOptions.swift#L331

**Comment by 1ec5** [comment]
For reference, MapboxGeocoder.swift uses a format string to truncate (not round) to five digits of precision:

https://github.com/mapbox/MapboxGeocoder.swift/blob/c5fcfe127b0b2c07b7bd9d5006f7f4fe0dc04b27/MapboxGeocoder/MBGeocodeOptions.swift#L185
