### ISSUE TITLE
Directions.calculate can fail silently.

### ISSUE THREAD

**Issue by JThramer** [mapbox/MapboxDirections.swift#310]
There are situations where the API can send us back a `200` (or some other status code that `URLSession` does not catch, such as `413`) that contains a response, but no routes.

This effectively forces the user to sanity-check that `routes` (in the completion handler) is not `nil`. This shouldn't have to happen. If we don't see a naturally-generated `URLError` come back from the response, we should synthesize one that represents the erroneous state of "No navigation solution came back from the service."

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
> There are situations where the API can send us back a `200` (or some other status code that `URLSession` does not catch, such as `413`) that contains a response, but no routes.

The Directions API returns HTTP 404 when the profile is unrecognized but HTTP 200 for a valid profile, even if there’s no route.

https://github.com/mapbox/MapboxDirections.swift/blob/6bf93daa11ed21b2b31352f199ac1316fb1c287b/MapboxDirections/MBDirections.swift#L289-L297

The profile identifier is part of the path, so an unrecognized path is like a nonexistent file on the server, so the reasoning goes. A valid profile that comes back with no route is like an empty but otherwise valid webpage. To the extent that this distinction makes sense when working directly with the API, it makes much less sense when using a client library that hides the request URL structure from the developer.

> This effectively forces the user to sanity-check that `routes` (in the completion handler) is not `nil`. This shouldn't have to happen.

The developer already has to account for `nil`, because `routes` is optional in Swift and nullable in Objective-C. But `nil` only happens when there’s an error; otherwise, it’s an empty array:

https://github.com/mapbox/MapboxDirections.swift/blob/6bf93daa11ed21b2b31352f199ac1316fb1c287b/MapboxDirections/MBDirections.swift#L70

Technically, the developer does have to account for `routes.first` being optional, but `routes[0]` is just as likely and gets around that optionality check.
