### ISSUE TITLE
Offline download task methods masquerade as action methods

### ISSUE THREAD

**Issue by 1ec5** [mapbox/MapboxDirections.swift#352]
`Directions.fetchAvailableOfflineVersions(completionHandler:)` and `Directions.downloadTiles(in:version:session:completionHandler:)` are named as if they actually start off an HTTP request, but all they do is create and return a URLSessionDownloadTask. That, combined with the fact that a completion handler will typically be a bit lengthy, means it’s extremely easy for the caller to forget to `resume()` the task. Nothing happens, and it takes many breakpoints and a modicum of hairpulling to figure out why. These methods should either be renamed to  `availableVersionsDownloadTask(completionHandler:)` and `downloadTask(forDownloadingTilesIn:version:session:completionHandler:)`, respectively, or they should resume the tasks before returning them, as `calculate(_:completionHandler:)` does.

/cc @mapbox/navigation-ios

**Comment by akitchen** [comment]
I agree - we should either hide (and handle) the data task implementation detail, or rename to be more idiomatic.

Earlier in the offline routing integration @frederoni and I were debating whether developers would need to pause/resume/cancel these potentially long-running tasks, or otherwise control their execution.

I suggest we refactor this in a mostly non-breaking way, by having the existing imperative methods wrap a new method which produces the task, and calls `-resume` on it before returning. This should preserve the flexibility while also providing a more expected default semantic
