### ISSUE TITLE
Xcode 11: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by lakersr8ers** [mapbox/MapboxDirections.swift#390]
Seeing this error when I try to use MapboxDirections within Xcode 11. Looks like this package needs to be built with the newest Xcode.

**Comment by 1ec5** [comment]
It sounds like you installed this library using Carthage. We only distribute this library as source, not as a binary, so the error is actually caused by your Carthage package cache going stale after upgrading Xcode. Try deleting Carthage/Build/iOS/MapboxDirections.framework* or running `carthage bootstrap` without the `--cache-builds` flag.
