### ISSUE TITLE
Directions returned are nil

### ISSUE THREAD

**Issue by madsodgaard** [mapbox/MapboxDirections.swift#48]
Hello, I am using the code you have supplied in your README example. When I debug the code, "waypoints" is nil, "error" is nil, "routes" are nil,

Its the exact same code

**Comment by 1ec5** [comment]
@madsodgaard, the library was just rewritten in #47. Are you using version 0.5.0 or the latest version in the master branch? If you run the example application, do you see any output?

**Comment by 1ec5** [comment]
In particular, make sure you’ve entered your access token in the placeholder.

**Comment by madsodgaard** [comment]
@1ec5 yes, I just updated the library a few moments ago. You example swift application works fine, do you think it has something to do that I am using the library in an Objective-C project?

**Comment by 1ec5** [comment]
Can you make sure you’ve updated to 4ed92bf692e2ea120c972041d56e6ea92fda2d34? There was a problem preventing `error` from being set.

**Comment by madsodgaard** [comment]
Okay, that seemed to fix the "error" variable, 
this is the content of the variable:
error	NSError *	domain: "MBDirectionsErrorDomain" - code: 18446744073709551615	0x0000000158253da0

**Comment by madsodgaard** [comment]
Error generating route, Error Domain=MBDirectionsErrorDomain Code=-1 "Not Found" UserInfo={NSLocalizedFailureReason=Not Found}

**Comment by 1ec5** [comment]
Would you mind providing the return value of `Directions.URLForCalculatingDirections(options:)`? Thanks! (Remember to remove your access token from the URL before commenting.)

**Comment by madsodgaard** [comment]
https://api.mapbox.com/directions/v5/test/-77.0324047,38.9131752%3B-77.0365,38.8977.json?alternatives=false&geometries=polyline&overview=simplified&steps=true&continue_straight=false&access_token=x

**Comment by 1ec5** [comment]
Ah, the problem is that `profileIdentifier` is set to `test`. As noted in the Quick Help documentation for that property and the `RouteOptions` initializer you’re using, the valid values are `MBDirectionsProfileIdentifierAutomobile`, `MBDirectionsProfileIdentifierCycling`, and `MBDirectionsProfileIdentifierWalking`. `MBDirectionsProfileIdentifierAutomobile` is the default. The library doesn’t assert that you’re using a different value, because we expect that more profiles may be added to the API in the future.

**Comment by madsodgaard** [comment]
Oh, sorry about that. I thought the variable was a unique identifier for the route!

However when I try to use the values you specified, it throws "use of undeclared identifier "MBDirectionsProfileIdentifierWalking"

**Comment by madsodgaard** [comment]
How would I go about drawing the route on the map, or does it does that by it self?

**Comment by 1ec5** [comment]
This library doesn’t handle drawing the route on the map, but it does give you the data you need to do it. Using the [Mapbox iOS SDK](https://www.mapbox.com/ios-sdk/) or [Mapbox OS X SDK](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/osx), you’d turn it into a polyline annotation like this:

```objc
// route is a Route
// mapView is an MGLMapView

// Convert the route’s coordinates into a polyline.
CLLocationCoordinate2D *routeCoordinates = malloc(route.coordinateCount * sizeof(CLLocationCoordinate2D));
[route getCoordinates:routeCoordinates];
MGLPolyline *routeLine = [MGLPolyline polylineWithCoordinates:routeCoordinates count:route.coordinateCount];

// Add the polyline to the map and fit the viewport to the polyline.
[mapView addAnnotation:routeLine];
[mapView setVisibleCoordinates:routeCoordinates count:route.coordinateCount edgePadding:UIEdgeInsetsZero animated:YES];

// Make sure to free this array to avoid leaking memory.
free(routeCoordinates);
```

By default, the coordinate array is simplified to minimize data usage. That should be fine if you’re showing the entire route on the map at once. If you need to zoom in on a specific portion of the route line, you can set the RouteOptions object’s `routeShapeResolution` property to `MBRouteShapeResolutionFull`.

**Comment by madsodgaard** [comment]
Hey again, since I've fixed the other error the API link now returns a new one:

{"code":"NoSegment","message":"Could not find a matching segment for input coordinates","routes":[]}

**Comment by 1ec5** [comment]
The error’s `localizedFailureReason` and `localizedRecoverySuggestion` properties provide a little more information. Essentially, one of the coordinates you’ve passed in is too far from the nearest road. You can increase the search radius around that coordinate by setting the `MBWaypoint` object’s `coordinateAccuracy` property.

If you’ve created the `MBRouteOptions` object using `CLLocation`s you’ve obtained from CLLocationManager, see [this important note](https://github.com/mapbox/MapboxDirections.swift/blob/fd1bc551cfcdf0d5fe06d3cdac35508d45a4a121/MapboxDirections/MBRouteOptions.swift#L145) (also in Quick Help) about CLLocation’s `horizontalAccuracy` property. The least tricky way to create a `MBRouteOptions` object is in fact to pass in `CLLocationCoordinate2D`s instead of `CLLocation`s.

**Comment by madsodgaard** [comment]
Okay, I fixed it by increasing the range with waypoint.coordinateaccuracy.

Just a last quick thing, my debug console is constantly getting spammed  [ERROR] {Map}[OpenGL]: stencil mask overflow - I've looked around in map box issues on github, and other people had them swell, but I can't find any fix for it.

**Comment by 1ec5** [comment]
Yes, this is being tracked in mapbox/mapbox-gl-native#962. Unfortunately I don’t have a workaround for you at this point. Perhaps using the `routeShapeResolution` of `MBRouteShapeResolutionSimplified` could work around the issue, since the route geometry is considerably simpler that way.

**Comment by madsodgaard** [comment]
I don't think it has something to do with the route, it still said it before I added the routing-system. Just when I had a regular map with annotations, and I moved around and zoomed.
