### ISSUE TITLE
sample code for routeCoordinates not working

### ISSUE THREAD

**Issue by MadeByDouglas** [mapbox/MapboxDirections.swift#56]
Under the section "Drawing the route on a map" the following snippet is listed:

```
if route.coordinateCount > 0 {
    // Convert the route’s coordinates into a polyline.
    var routeCoordinates = route.coordinates!
    let routeLine = MGLPolyline(coordinates: &routeCoordinates, count: route.coordinateCount)

    // Add the polyline to the map and fit the viewport to the polyline.
    mapView.addAnnotation(routeLine)
    mapView.setVisibleCoordinates(routeCoordinates, count: route.coordinateCount, edgePadding:                 UIEdgeInsetsZero, animated: true)
}
```
the var routeCoordinates is an array with CLLocationCoordinate2D objects, however the method setVisibleCoordinates() first parameter is just CLLocationCoordinate2D. 

I am not sure if i should be iterating through and updating the visible coordinates based on each one in the array, however, even when i try to just say like the first object of the array it still gives me an error which seems to be related to objC. It says it wants mutablePointer CLLocationCoordinate2D, and i'm not sure what to do there. 

Is this code wrong or am I missing something?

**Comment by 1ec5** [comment]
There’s a typo in the example code. I’ve pushed a fix to the documentation in fdbabf2621117f17178c394eb1047fede4eb55df, part of #57.

**Comment by 1ec5** [comment]
OK, I’ve fixed the documentation.

The compiler’s error messages aren’t particularly helpful in this case, so thanks for asking about it. When you see a mutable pointer in the parameter of a method bridged from Objective-C, usually it’s either because the Objective-C method expects a C array or because it’s an in-out parameter. In this case, the method expects a C array containing all the coordinates. You can convert a Swift array such as `route.coordinates` into a C array by storing it in a `var` and getting the `&` of it. The method wants a C array, rather than an NSArray (that would be bridged to a Swift `Array`), because `CLLocationCoordinate2D` is a C struct that can’t be stored in an NSArray. Hope this helps.

**Comment by MadeByDouglas** [comment]
ah ok, thanks so much! Yeah that makes sense, thank you for the apple doc too, i havent had much experience with C arrays and such so yeah i didnt know what the compiler was complaining about.
